name: iOS CI/CD Pipeline

on:
  push:
    branches: [main]   # Trigger CI on main pushes
  pull_request:
    branches: [main]   # Trigger on PRs to main

jobs:
  build:
    runs-on: macos-latest  # Use macOS runner for Xcode
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcodebuild -version

      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies -project Fleet_Master.xcodeproj


      - name: Build project
        run: |
          xcodebuild clean build \
          -project YourProject.xcodeproj \
          -scheme YourSchemeName \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -project YourProject.xcodeproj \
          -scheme YourSchemeName \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.2'

      - name: Archive App (Optional)
        run: |
          xcodebuild archive \
          -project YourProject.xcodeproj \
          -scheme YourSchemeName \
          -archivePath ${{ github.workspace }}/YourProject.xcarchive

